/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import InterfacesGraficas.EstadisticasPersonales;
import ajedrezpoo.Sistema;
import ajedrezpoo.Tablero;
import ajedrezpoo.Usuario;
import java.util.ArrayList;

/**
 *
 * @author balalo
 */
public class EstadisticasProblemas extends javax.swing.JDialog {
    Sistema sistema;
    Tablero tablero;
    Usuario usuario;
    java.awt.Frame parent;
    
    /**
     * Creates new form EstadisticasProblemas
     */
    public EstadisticasProblemas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
    }
    public EstadisticasProblemas(java.awt.Frame parent, boolean modal, Sistema sis, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        sistema= sis;
        this.usuario = usuario;
        ArrayList<Tablero> tableros = sistema.getTableros();
        Integer i=1;
        for(Tablero t : tableros){
            CajaConTableros.addItem("Tablero " + i.toString());
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CajaConTableros = new javax.swing.JComboBox<>();
        SeleccionarBoton = new javax.swing.JButton();
        ProblemaSeleccionado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numRes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PorcentajeExito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CajaConUsuarios = new javax.swing.JComboBox<>();
        SeleccionarUsuBoton = new javax.swing.JButton();
        VolverBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JugarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lista de problemas");

        SeleccionarBoton.setText("Seleccionar");
        SeleccionarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarBotonActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero total de Usuarios que lo ha resuelto:");

        jLabel3.setText("Porcentaje de éxito del problema");

        jLabel4.setText("Usuarios que han resuelto el problema:");

        SeleccionarUsuBoton.setText("Seleccionar");
        SeleccionarUsuBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarUsuBotonActionPerformed(evt);
            }
        });

        VolverBoton.setText("Volver");
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });

        jLabel5.setText("¿Quieres jugar este problema?");

        JugarBoton.setText("Jugar!");
        JugarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProblemaSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addComponent(CajaConTableros, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(SeleccionarBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CajaConUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(VolverBoton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numRes, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(PorcentajeExito))))
                        .addGap(33, 33, 33)
                        .addComponent(SeleccionarUsuBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addComponent(JugarBoton)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CajaConTableros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarBoton))
                .addGap(18, 18, 18)
                .addComponent(ProblemaSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PorcentajeExito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CajaConUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarUsuBoton))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JugarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(VolverBoton)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarBotonActionPerformed
        ArrayList<Tablero> tableros = sistema.getTableros();
        Integer opcion = CajaConTableros.getSelectedIndex();
        tablero = tableros.get(opcion);
        opcion += 1;//para que empiece a mostrar desde el tablero 1 no el 0
        ProblemaSeleccionado.setText("Tablero "+opcion.toString());
        Integer numResueltos=tablero.mostrarNumRes();
        numRes.setText(numResueltos.toString());
        numRes.setEditable(false);
        Double exito = tablero.porcentajeExito();
        PorcentajeExito.setText(exito.toString()+"%");
        PorcentajeExito.setEditable(false);
        ArrayList<Usuario> usuarios = tablero.getUsuariosResueltos();
        for(Usuario u : usuarios){
            CajaConUsuarios.addItem(u.getNombre());
        }
        
    }//GEN-LAST:event_SeleccionarBotonActionPerformed

    private void SeleccionarUsuBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarUsuBotonActionPerformed
        Integer opcion = CajaConUsuarios.getSelectedIndex();
        ArrayList<Usuario> usuarios = tablero.getUsuariosResueltos();
        Usuario usu = usuarios.get(opcion);
        EstadisticasPersonales estadisticas = new EstadisticasPersonales(parent,true,usu);
        estadisticas.setVisible(true);
    }//GEN-LAST:event_SeleccionarUsuBotonActionPerformed

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_VolverBotonActionPerformed

    private void JugarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarBotonActionPerformed
        Juego juego = new Juego(parent,true);
        juego.Jugar(tablero, usuario);
        juego.setVisible(true);//NO PERMITIR QUE JUEGUE SI NO HAY USUARIO
    }//GEN-LAST:event_JugarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadisticasProblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadisticasProblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadisticasProblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadisticasProblemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EstadisticasProblemas dialog = new EstadisticasProblemas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CajaConTableros;
    private javax.swing.JComboBox<String> CajaConUsuarios;
    private javax.swing.JButton JugarBoton;
    private javax.swing.JTextField PorcentajeExito;
    private javax.swing.JTextField ProblemaSeleccionado;
    private javax.swing.JButton SeleccionarBoton;
    private javax.swing.JButton SeleccionarUsuBoton;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField numRes;
    // End of variables declaration//GEN-END:variables
}
