/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import ajedrezpoo.Clasificacion;
import ajedrezpoo.Sistema;
import ajedrezpoo.TablaNoValidaException;
import ajedrezpoo.Tablero;
import ajedrezpoo.Usuario;
import ajedrezpoo.UsuarioNoEncontradoException;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author balalo
 */
public class InterfazGrafica extends javax.swing.JFrame {

    Sistema sistema;
    Usuario usuario;
    Clasificacion clasificacion;
    /**
     * Creates new form InterfazGráfica
     */
    public InterfazGrafica() {
        sistema = new Sistema();
        this.setTitle("Juego Ajedrez");
        this.setResizable(false);
        try{
            for (int i = 1; i<11; i++){
                String diezTableros = "tablero";
                diezTableros += Integer.toString(i);
                diezTableros += ".txt";
                sistema.añadirTablero(diezTableros);
            }
            ArrayList<Tablero> tableros = sistema.getTableros();
            Integer i=1;
            initComponents();//cuidado con cambiar las cosas de la interfaz grafica antes de inicializarla!!!
            CajaConTableros.addItem("Aleatorio");//La primera opcion es uno de los 10 problemas aleatorios de la pagina web.
            for(Tablero t : tableros){
                CajaConTableros.addItem("Tablero " + i.toString());
                i++;
            }
        }
        catch(java.io.FileNotFoundException fnfex){
            UltimaOperacion.setText("No se ha podido encontrar el archivo");
        } 
        catch (TablaNoValidaException ex) {
            UltimaOperacion.setText("Hay un tablero mal");
        }
        
        usuario = new Usuario();
        clasificacion= new Clasificacion();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CrearUsuarioBoton = new javax.swing.JButton();
        IniciarSesionBoton = new javax.swing.JButton();
        UltimaOperacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NombreUsuarioText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CajaConTableros = new javax.swing.JComboBox<>();
        JugarBoton = new javax.swing.JButton();
        EstadisticasPersonalesBoton = new javax.swing.JButton();
        EstadisticasProblemasBoton = new javax.swing.JButton();
        ClasificacionBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SubirProblemaText = new javax.swing.JTextField();
        SubirProblemaBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreGuardarArchivo = new javax.swing.JTextField();
        GuardarBoton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombreSubirArchivo = new javax.swing.JTextField();
        SubirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema"));

        CrearUsuarioBoton.setText("Crear Usuario");
        CrearUsuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBotonActionPerformed(evt);
            }
        });

        IniciarSesionBoton.setText("Iniciar Sesión");
        IniciarSesionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IniciarSesionBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearUsuarioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearUsuarioBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IniciarSesionBoton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        UltimaOperacion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        UltimaOperacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Usuario:");

        jLabel2.setText("¿Qué problema desea Jugar?");

        CajaConTableros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaConTablerosActionPerformed(evt);
            }
        });

        JugarBoton.setText("Jugar");
        JugarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarBotonActionPerformed(evt);
            }
        });

        EstadisticasPersonalesBoton.setText("Ver estadísticas personales");
        EstadisticasPersonalesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasPersonalesBotonActionPerformed(evt);
            }
        });

        EstadisticasProblemasBoton.setText("Ver estadísitcas de los problemas");
        EstadisticasProblemasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasProblemasBotonActionPerformed(evt);
            }
        });

        ClasificacionBoton.setText("Ver clasificación");
        ClasificacionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasificacionBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("¿Desea subir algun problema?");

        jLabel4.setText("Nombre del archivo:");

        SubirProblemaBoton.setText("Subir Problema");
        SubirProblemaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirProblemaBotonActionPerformed(evt);
            }
        });

        jLabel5.setText("¿Desea guardar los datos?");

        jLabel6.setText("Nombre del archivo que desea guardar:");

        GuardarBoton.setText("Guardar");
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });

        jLabel7.setText("¿Desea subir datos?");

        jLabel8.setText("Nombre del archivo que desea cargar:");

        SubirBoton.setText("Subir");
        SubirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClasificacionBoton)
                                    .addComponent(EstadisticasPersonalesBoton)
                                    .addComponent(EstadisticasProblemasBoton))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(UltimaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CajaConTableros, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NombreUsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JugarBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(67, 67, 67)
                                .addComponent(SubirProblemaText, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SubirProblemaBoton)
                                .addGap(107, 107, 107)))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuardarBoton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NombreGuardarArchivo)
                                .addComponent(jLabel6))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(NombreSubirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubirBoton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreUsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(SubirProblemaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SubirProblemaBoton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(CajaConTableros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JugarBoton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UltimaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EstadisticasPersonalesBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EstadisticasProblemasBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClasificacionBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreGuardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreSubirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GuardarBoton)
                            .addComponent(SubirBoton))))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBotonActionPerformed
        CrearUsu usuario = new CrearUsu();

        if(JOptionPane.showConfirmDialog(this, usuario, "Introduzca datos",
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
        == JOptionPane.OK_OPTION) {

        /* El primer argumento es la ventana padre (this, normalmente). El segundo argumento es el objeto recién creado, una instancia del panel. 
           El tercer argumento es el título del panel. El cuarto argumento decide qué elementos prediseñados tendrá el panel. 
           El quinto argumento refleja el tipo del panel: de error, de aviso, normal, etc.) */

        /* El método devuelve la opción escogida por el usuario (Aceptar o Cancelar). Por tanto, aquí va el código que se ejecutará si se pulsa OK en el panel.*/

        //Recogida datos  
        if(!usuario.getNombre().equals("") && !usuario.getContraseña().equals("")){
            String nombreUsu = usuario.getNombre();
            String contraseñaUsu = usuario.getContraseña();
            Usuario usu = new Usuario(nombreUsu, contraseñaUsu);
            sistema.añadirUsuario(usu);// TODO add your handling code here:
            UltimaOperacion.setText ("Ultima operacion: usuario creado");
            clasificacion.AñadirUsu(usu);
            this.usuario = usu;
            NombreUsuarioText.setText(usu.toString());
        }
        else
            UltimaOperacion.setText("El usuario introducido es nulo");
        NombreUsuarioText.setEditable(false);
        }
    }//GEN-LAST:event_CrearUsuarioBotonActionPerformed

    private void IniciarSesionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionBotonActionPerformed
        IniciarSesion sesion = new IniciarSesion();
        
        if(JOptionPane.showConfirmDialog(this, sesion, "Introduzca datos",
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE)
        == JOptionPane.OK_OPTION) {
        
        String nombreUsu = sesion.getNombre();
        String contraseñaUsu = sesion.getContraseña();
        
        try{
            Usuario usu = sistema.autenticar(nombreUsu, contraseñaUsu);
            this.usuario = usu;
            NombreUsuarioText.setText(usu.toString());
            UltimaOperacion.setText ("Ultima operacion: sesion iniciada");
            
        }
        catch(UsuarioNoEncontradoException e1){
            UltimaOperacion.setText ("Nombre de usuario / contraseña incorrecto(s)");
        }
        }
    }//GEN-LAST:event_IniciarSesionBotonActionPerformed

    private void CajaConTablerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaConTablerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaConTablerosActionPerformed

    private void JugarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarBotonActionPerformed
        try{
            Usuario usu = sistema.autenticar(usuario.getNombre(), usuario.getPassword());
            ArrayList<Tablero> tableros = sistema.getTableros();
            int opcion = CajaConTableros.getSelectedIndex();//vemos la opcion que se toma en la ComboBox
            Tablero tablero;//inicializamos
            if (opcion == 0){
                int random = (int) (Math.random() * 10);
                tablero = tableros.get(random);
            }
            else{
                tablero = tableros.get(opcion-1);}//como el primer indice va a ser el 1 cojo el x-1
            Juego juego = new Juego(this,true);
            juego.Jugar(tablero, usuario);
            juego.setVisible(true);//NO PERMITIR QUE JUEGUE SI NO HAY USUARIO
        }
        catch(UsuarioNoEncontradoException a){
            UltimaOperacion.setText("No se ha metido ningun usuario");
        }
    }//GEN-LAST:event_JugarBotonActionPerformed

    private void EstadisticasPersonalesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasPersonalesBotonActionPerformed
        EstadisticasPersonales estadisticas = new EstadisticasPersonales(this,true,usuario);
        estadisticas.setVisible(true);
//        estadisticas.mensaje(usuario);
    }//GEN-LAST:event_EstadisticasPersonalesBotonActionPerformed

    private void EstadisticasProblemasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasProblemasBotonActionPerformed
        EstadisticasProblemas estadisticas = new EstadisticasProblemas(this,true,sistema,usuario);
        estadisticas.setVisible(true);
    }//GEN-LAST:event_EstadisticasProblemasBotonActionPerformed

    private void ClasificacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasificacionBotonActionPerformed
        ClasificacionInterfaz estadisticas = new ClasificacionInterfaz(this,true,clasificacion);
        estadisticas.setVisible(true);
    }//GEN-LAST:event_ClasificacionBotonActionPerformed

    private void SubirProblemaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirProblemaBotonActionPerformed
    try{
        String nombreArchivo = SubirProblemaText.getText();
        sistema.añadirTablero(nombreArchivo);
        CajaConTableros.addItem(nombreArchivo);
        UltimaOperacion.setText("Se ha subido el problema");
        
    }
    catch(java.io.FileNotFoundException fnfex){
        UltimaOperacion.setText("No se ha podido guardar el archivo");
    }   
    catch (TablaNoValidaException ex) {
            UltimaOperacion.setText("No se ha podido añadir");
        }
    }//GEN-LAST:event_SubirProblemaBotonActionPerformed

    private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
        String nombreArchivo = NombreGuardarArchivo.getText();
//        String ultimoTramo = nombreArchivo.substring(nombreArchivo.length()-4, nombreArchivo.length());
//        if(!ultimoTramo.equals(".ser"))
//            nombreArchivo+=".ser";
        try{
            File fichero = new File(nombreArchivo);
            fichero.createNewFile();
            FileOutputStream FileEscribir = new FileOutputStream(fichero, false);
            ObjectOutputStream Output = new ObjectOutputStream(FileEscribir);


            Output.writeObject(sistema);
            Output.close();
            UltimaOperacion.setText("Se ha guardado el archivo correctamente");
    
        }
        catch(IOException io){
            UltimaOperacion.setText("No se ha podido guardar");
        }
    }//GEN-LAST:event_GuardarBotonActionPerformed

    private void SubirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirBotonActionPerformed
        try{
        FileInputStream FileLeer = new FileInputStream(NombreSubirArchivo.getText());
        ObjectInputStream Input = new ObjectInputStream(FileLeer);
        
        sistema = (Sistema) Input.readObject();
        Input.close();
        UltimaOperacion.setText("Se ha subido correctamente");
        }
        catch(IOException io){
            UltimaOperacion.setText("No se ha encontrado el archivo");
        } catch (ClassNotFoundException ex) {
            UltimaOperacion.setText("El fichero no es compatible");
        }

        
    }//GEN-LAST:event_SubirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CajaConTableros;
    private javax.swing.JButton ClasificacionBoton;
    private javax.swing.JButton CrearUsuarioBoton;
    private javax.swing.JButton EstadisticasPersonalesBoton;
    private javax.swing.JButton EstadisticasProblemasBoton;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JButton IniciarSesionBoton;
    private javax.swing.JButton JugarBoton;
    private javax.swing.JTextField NombreGuardarArchivo;
    private javax.swing.JTextField NombreSubirArchivo;
    private javax.swing.JTextField NombreUsuarioText;
    private javax.swing.JButton SubirBoton;
    private javax.swing.JButton SubirProblemaBoton;
    private javax.swing.JTextField SubirProblemaText;
    private javax.swing.JLabel UltimaOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
